services:
  expressvpn:
    image: frankli/expressvpn:latest
    container_name: expressvpn
    restart: always
    environment:
      - EXPRESSVPN_ACTIVATION_CODE={{you own activation code}} # ExpressVPN activation code: https://www.expressvpn.com/support/troubleshooting/find-activation-code/
      - CONNECT_LOCATION=smart
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    tty: true
    privileged: true
    networks:
      - vpn_network
    healthcheck:
      test: /opt/expressvpn/bin/expressvpnctl status | grep -q "Connected"
      interval: 60s
      timeout: 10s
      retries: 20
      start_period: 120s

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:expressvpn"
    depends_on:
      expressvpn:
        condition: service_healthy
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8060
    volumes:
      - ./config:/config
      - /vol1/1000/Downloads:/downloads
      - ./vuetorrent:/vuetorrent
    healthcheck:
      test: >
        sh -c '
          wget -q --spider http://localhost:8060/ || exit 1
        '
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 10s

  qbt-proxy:
    image: alpine/socat
    container_name: qbt-proxy
    restart: always
    depends_on:
      expressvpn:
        condition: service_healthy
      qbittorrent:
        condition: service_healthy
    networks:
      - vpn_network
    ports:
      - "8060:8060"
    command: tcp-listen:8060,fork,reuseaddr tcp-connect:expressvpn:8060
    healthcheck:
      test: >
        sh -c '
          nc -z localhost 8060 || exit 1
        '
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 10s
  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all 
      - AUTOHEAL_INTERVAL=30 
      - AUTOHEAL_START_PERIOD=180
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  vpn_network:
    driver: bridge


